#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yq
Version  : 2.13.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/77/8f/b7e9da70e379a0250096b953fa40f504a99bddd641b373cd99f8e0417c3d/yq-2.13.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/77/8f/b7e9da70e379a0250096b953fa40f504a99bddd641b373cd99f8e0417c3d/yq-2.13.0.tar.gz
Summary  : Command-line YAML/XML processor - jq wrapper for YAML/XML documents
Group    : Development/Tools
License  : Apache-2.0
Requires: yq-bin = %{version}-%{release}
Requires: yq-license = %{version}-%{release}
Requires: yq-python = %{version}-%{release}
Requires: yq-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(argcomplete)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(toml)
BuildRequires : pypi(xmltodict)

%description
yq: Command-line YAML/XML/TOML processor - jq wrapper for YAML, XML, TOML documents
===================================================================================

%package bin
Summary: bin components for the yq package.
Group: Binaries
Requires: yq-license = %{version}-%{release}

%description bin
bin components for the yq package.


%package license
Summary: license components for the yq package.
Group: Default

%description license
license components for the yq package.


%package python
Summary: python components for the yq package.
Group: Default
Requires: yq-python3 = %{version}-%{release}

%description python
python components for the yq package.


%package python3
Summary: python3 components for the yq package.
Group: Default
Requires: python3-core
Provides: pypi(yq)
Requires: pypi(argcomplete)
Requires: pypi(pyyaml)
Requires: pypi(toml)
Requires: pypi(xmltodict)

%description python3
python3 components for the yq package.


%prep
%setup -q -n yq-2.13.0
cd %{_builddir}/yq-2.13.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1638523932
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yq
cp %{_builddir}/yq-2.13.0/LICENSE %{buildroot}/usr/share/package-licenses/yq/172ca3bbafe312a1cf09cfff26953db2f425c28e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tomlq
/usr/bin/xq
/usr/bin/yq

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yq/172ca3bbafe312a1cf09cfff26953db2f425c28e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
